steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "${_SERVICE_NAME}"
      - "--source=./python-backend"
      - "--region=southamerica-east1"
      - "--platform=managed"
      - "--allow-unauthenticated"
